### ISSUE TITLE
Section id definition

### ISSUE THREAD

**Issue by wvangeit** [AllenInstitute/sonata#16] opened 2018-04-24 13:02 UTC
I could be wrong, but I don't see any place in the SONATA document where the concept of a 'section id' is specified in detail. The term is mentioned here:
https://github.com/AllenInstitute/sonata/blame/master/docs/SONATA_DEVELOPER_GUIDE.md#L851

NEURON first loads the sections from the morphology file in lists in the following order: soma, axon, basal, apical. Then it loops through all these lists one by one, and assigns section ids to ever section.
This is how the BBP simulator code interprets the section ids.
I'm not 100% sure if this conforms with the way the section ids are provided by the ABI in the edge files.
Mentioning it because it might be difficult to debug if we get this slightly wrong.

**Comment by hernando** [comment] 2018-04-24 16:11
Something related to this was discussed long time ago in the context of morphology modifications, but not conclusion was reached.

The section ID could be clarified by giving an example. However, the specification that you're requesting is beyond disambiguating what a section is and I'm afraid that it's beyond the scope of the current spec.
My understanding of the file format description is that it's the users' responsibility to ensure that section Ids are consistently interpreted by their tools. The only way the specification could ensure this is by stating a very well defined iteration order of sections in a morphology and possibly enforcing it as an additional restriction of the .swc files used. This ordering can be easily conflicting with the logic that tools such as Neuron implement, so in the end it's better to not state anything in the specification.

**Comment by hernando** [comment] 2018-04-24 16:11
Unless anybody has a different opinion, I'm going to close the ticket.

**Comment by wvangeit** [comment] 2018-04-24 17:48
I don't really understand this reasoning. So how will we make sure the synapses are placed at the correct location ? Currently we have sec id values in a file specified by the SONATA format, but people have no idea what they mean.
If this reasoning is followed all the way, why do we specify 'anything' in the document. If users just implicitly agree on what all the values mean, we don't need any definition (for e.g. sec_x, syn_weight, diameters, swc requirements, etc).

**Comment by hernando** [comment] 2018-04-24 19:55
Sorry, I see your point now, I was unconsciously assuming that morphologies are stored in our internal .h5 format, where section IDs are clearly specified.

Let's leave Neuron out of the picture for the moment for simplicity.
Under the assumption of section ids being stored in the morphology files, it's clearly the user's responsibility to make sure that sec_id from the edges.h5 file and the morphology files match. In this regard, the spec can't do anything beyond a recommendation. All tools would be assumed to consume .h5 morphologies for consistency.
However, this is not the case, and SONATA chooses .swc to store morphologies, a format with undefined section ids. In order to assign ids to sections, we must specify how sections are numerated while parsing the .swc file. Here I agree with you that this is missing in the spec.
We could specify an enumeration method, but I'm afraid that in fact no single method would be sufficient and we would need to add a new attribute to the edges file that says which was the enumeration method use to place synapses on sections. The reason for requiring this complexity is software like NEURON.

NEURON messes it all up because it defines its own method of enumerating sections. The description you gave is not even sufficient for me to know 100% sure how to implement the same thing that NEURON does, even less writing a spec that describes it (e.g. are sections of a given type enumerated breadth first, depth first or in the order in which they appear in the file). So, what should the spec do about this? My suggestions would be:
* Allow different methods as I said above and let the user choose the most convenient for his case. This will limit which simulators may be used with a given circuit description, but I guess that's pretty much the case already if models are not converted.
* Describe what NEURON does and impose it to all other tools (but then what to do when using simulators that cannot be adapted)
* Do nothing and let the user figure it out (but adding a note and this issue, so people at least know better what section_ids are).

I'd go for the first one, but this will make swc parsing a non trivial task anymore, as many people assume (well, in my opinion it never was unless you make assumptions).

In any case, the spec cannot enforce consistency. A consumer of the circuit has to trust that the information in the edges file is consistent with his view of section ids for the .swc morphologies. 

As a side note, defining an enumeration method for sections is tricky, there are plenty of questions that come to my mind.
* Do you want the method to assign unique ids for all the possible valid representations of the same morphology as a .swc file?
* Do you want to enforce additional restrictions on the .swc file so enumerating by the order of appearance in the file is sufficient?
* Is any of this compatible with what NEURON does?
* Can we ensure/should we enforce that tools that modify morphologies without changing the structure keep the enumeration stable?
* ...

**Comment by wvangeit** [comment] 2018-04-25 10:32
Yes, sonata obviously can't use the h5 format because it is a closed format. Neuromorpho e.g. has a massive amount of swc morphs, so it seems that was the right choice.
Maybe I should correct myself a little bit. It's not really NEURON that assigns sec ids, it's something that was added later in Neurodamus, H5 format, etc, but is based on how Neuron stores the sections. I would say it's actually 'cleaner' this way, because it sorts per section type, but I guess that's up for interpretation.
Anyhow, I would also go for the first option you suggest. We allow for different methods. My preference would be to provide a little code snippet that reads an swc file and assigns the sec ids, but I'm not sure that's appropriate. The text for our case would also be fairly simple.

About your questions:
1) yes, if the swc file changes in any way, the sectionids might change
2) that's another option, if we enforce that the order is soma, axon, basal, apical the problem almost disappears. It will only require users to convert their morphs beforehand, and requires some scripts that check the format, not sure if its worth the effort though.
3) yes, NEURON's algorithm is pretty straightforward: number based on appearance, but inside the four soma, axon, basal, apic subgroups
4) yes, I think we should, especially tools that e.g. convert to H5 files. But I'm not sure this is a problem for the format description. Obviously all tools should follow the 'ground truth' provided by the files provided in the sonata format.

**Comment by wvangeit** [comment] 2018-05-02 11:47
Just mentioning it here for future reference. We saw that the HOC code that generates all our h5 morphs explicitly saves the sections in the order soma, axon, basal, apical. So although this is not part of the h5 morph format description, in practice this is how all these files look like.
We will have to be careful to maintain this ordering because tools might break / become inconsistent otherwise.

**Comment by arsenius7** [comment] 2018-05-02 13:25
For at least some of SWC in the test SONATA circuit, sections go in that order: `soma, basal_dendrite, axon, basal_dendrite, apical_dendrite, basal_dendrite`.

**Comment by wvangeit** [comment] 2018-05-02 13:28
yes, this is basically (without explicitly mentioning it), that I started this issue, because I guess we're going to get the secids wrong for that circuit.

**Comment by hernando** [comment] 2018-05-02 13:29
I'd like to hear the opinion of somebody from the Allen Institute (@kaeldai?) because this issues it not a trivial modification of the spec.

**Comment by kaeldai** [comment] 2018-05-03 22:53
Honestly, at the Allen Institute we really never ran into this issue because we never used sec_id to place synapses on our models. For the majority of our models we specify the section (basal, apical, etc), an arc-distance range, and a random-number seed which we use to populate our synapses. It works well for us, although you can't control which branch a synapse gets placed on which I believe is the reason it rejected for Sonata. @V0L1T10N may want to chime in as well.

Having users specify sec_id and sec_x is a new feature that's not being used. I'd image that internally we'll continue to specify arc-distance range - it's more intuitive, more robust in terms of not having to worry about the internal workings of NEURON, and significantly faster. Though for external use and collaboration we'll go ahead and use sec_id's.

**Comment by wvangeit** [comment] 2018-05-04 09:10
Ok. Can you specify how you determined the sec_ids you used in the files of this circuit. Are they based on the 'pure' locations in the SWC files, are preordered per soma,axon,basal,apical ?

**Comment by kaeldai** [comment] 2018-05-04 17:36
For this circuit I just uniformly randomly assigned the locations of synapses everywhere expect the axon. Upon further analysis I noticed that there was one synapse directly on the soma. Per @CellAssembly instructions I am going to regenerate the network not to include somatic synapses and cluster the connections a little better.

**Comment by CellAssembly** [comment] 2018-05-04 18:00
For the files that we sent you, after generating uniformly at random as mentioned above, we simply save the network exactly as it was generated by NEURON. @kaeldai can confirm.

**Comment by V0L1T10N** [comment] 2018-05-04 21:05
Sections are ordered based on NEURON's internal ordering when running the
loop over sections and segments of the cell
for sec in hoc_object.all:
    for seg in sec:

For us it did not matter how the sec_ids are assigned to the sections,
because we did not use

**Comment by V0L1T10N** [comment] 2018-05-04 21:16
Sorry I managed to send an incomplete email. Below is the complete version:


Sections and segments are ordered using NEURON's internal ordering when
running the loop over sections and segments of the cell's hoc object:
for sec in hoc_object.all:
    for seg in sec:
        do something
Thus we get arrays over segments with the index being a segment_id.  The
section_id is not necessary and was not used, because segment_id uniquely
defines a location on a cell.

Sergey

**Comment by wvangeit** [comment] 2018-05-07 09:15
Ok. Thanks for the info. So just to be 100%, @V0L1T10N, you mean with 'was not used' in
>  The
section_id is not necessary and was not used, because segment_id uniquely
defines a location on a cell.

that the section_id 'were not used in the simulator on our side'. But the sec_ids in the SONATA files you sent us are still correct, and defined by Neuron, right ?

**Comment by jdcourcol** [comment] 2018-05-09 12:11
@hernando : I assume you have an issue if you are displaying a compartment report ?

**Comment by hernando** [comment] 2018-05-14 11:07
@jdcourcol not really. Edge files are not used to apply simulation data on geometrical models. From the description above it doesn't look like there would be any problem for displaying a compartment report.

**Comment by hernando** [comment] 2018-05-15 14:30
Thinking about it again, the problems that you have in mind are exactly what was discussed at the top of the issue. The options remain the same as I mentioned [above](https://github.com/AllenInstitute/sonata/issues/16#issuecomment-384059317). I'd vote for extending the spec to describe the section enumeration methods and add a field in the circuit configuration to say which one applies.

**Comment by hernando** [comment] 2018-10-15 07:59
The final decision has been to describe in the spec a single section numbering algorithm which in fact is what NEURON does. Fixed by #26

**Closed by hernando** 2018-10-15 07:59 UTC
